---
root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - jest
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - prettier
rules:
  indent: ['error', 2]
  quotes: ['error', 'single']
  semi: ['error', 'never']
